#!/usr/bin/env python3
"""
build_standalone.py — Generate a self-contained HTML file.

Embeds result_filtered.json directly into predictor_browser.html so that
users only need to download a SINGLE file to view results.

Usage:
    python build_standalone.py
    python build_standalone.py --html predictor_browser.html --json result_filtered.json --out predictor_browser_standalone.html
"""
import argparse
import json
import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Marker placed in predictor_browser.html to indicate where embedded data goes.
EMBED_MARKER = "// EMBED_POINT"


def build(html_path: str, json_path: str, out_path: str) -> None:
    try:
        with open(html_path, "r", encoding="utf-8") as f:
            html = f.read()
    except OSError as exc:
        print(f"ERROR: cannot read HTML template '{html_path}': {exc}", file=sys.stderr)
        sys.exit(1)

    try:
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except OSError as exc:
        print(f"ERROR: cannot read JSON data '{json_path}': {exc}", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as exc:
        print(f"ERROR: invalid JSON in '{json_path}': {exc}", file=sys.stderr)
        sys.exit(1)

    # Compact JSON (no whitespace) — intentionally minified to reduce file size.
    json_str = json.dumps(data, ensure_ascii=False, separators=(",", ":"))

    # --- hide the file-drop zone using the CSS class defined in the template ---
    html = html.replace(
        '<div id="dropZone">',
        '<div id="dropZone" class="hidden">',
    )

    # --- inject embedded data + auto-load logic at the designated marker ---
    auto_load_js = f"""
// ── Embedded data (generated by build_standalone.py) ──────────────
const EMBEDDED_DATA = {json_str};

window.addEventListener('DOMContentLoaded', function() {{
  const banner = document.createElement('div');
  banner.style.cssText = 'background:#0d3b2e;border:1px solid #1e7a4e;border-radius:12px;padding:14px 18px;margin-bottom:16px;color:#7dd3b0;font-size:.9rem;text-align:center';
  banner.innerHTML = '✅ <strong>הנתונים כבר מוטמעים בקובץ זה</strong> — אין צורך לטעון קובץ נפרד';
  const dropZone = document.getElementById('dropZone');
  if (dropZone && dropZone.parentNode) {{
    dropZone.parentNode.insertBefore(banner, dropZone);
  }}

  if (EMBEDDED_DATA && Array.isArray(EMBEDDED_DATA.messages)) {{
    loadedMessages = EMBEDDED_DATA.messages;
    showStatus('✅ נטענו ' + loadedMessages.length + ' הודעות (מוטמע)');
    setTimeout(hideStatus, 2500);
    buildTargetDropdown();
    document.getElementById('settings').classList.add('visible');
    runAnalysis();
  }}
}});
"""

    if EMBED_MARKER not in html:
        print(
            f"ERROR: embed marker '{EMBED_MARKER}' not found in template. "
            "Please ensure predictor_browser.html contains this marker.",
            file=sys.stderr,
        )
        sys.exit(1)

    html = html.replace(EMBED_MARKER, auto_load_js.rstrip())

    # Update the page title and subtitle to mention it's standalone
    html = html.replace(
        "<title>ניתוח מנבאי אזעקות 🎯</title>",
        "<title>ניתוח מנבאי אזעקות 🎯 (קובץ עצמאי)</title>",
    )
    html = html.replace(
        "טען קובץ ייצוא טלגרם · הכל רץ בדפדפן · אין צורך ב-Python או חיבור לאינטרנט",
        "הנתונים מוטמעים בקובץ · הכל רץ בדפדפן · אין צורך ב-Python, חיבור לאינטרנט, או קובץ נוסף",
    )

    try:
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(html)
    except OSError as exc:
        print(f"ERROR: cannot write output '{out_path}': {exc}", file=sys.stderr)
        sys.exit(1)

    size_kb = os.path.getsize(out_path) / 1024
    print(f"✅ נוצר: {out_path}  ({size_kb:.1f} KB)")
    print(f"   HTML מקורי: {os.path.getsize(html_path) / 1024:.1f} KB")
    print(f"   JSON מוטמע: {os.path.getsize(json_path) / 1024:.1f} KB")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a standalone self-contained HTML viewer")
    parser.add_argument("--html", default=os.path.join(SCRIPT_DIR, "predictor_browser.html"))
    parser.add_argument("--json", default=os.path.join(SCRIPT_DIR, "result_filtered.json"))
    parser.add_argument("--out", default=os.path.join(SCRIPT_DIR, "predictor_browser_standalone.html"))
    args = parser.parse_args()

    for path, label in [(args.html, "--html"), (args.json, "--json")]:
        if not os.path.isfile(path):
            print(f"ERROR: {label} file not found: {path}", file=sys.stderr)
            sys.exit(1)

    build(args.html, args.json, args.out)


if __name__ == "__main__":
    main()
